[build-system]
requires = ["scikit-build-core >=0.4.3", "nanobind >=1.3.2"]
build-backend = "scikit_build_core.build"

[project]
name = "othello_mcts"
version = "0.1.0"
dependencies = []
requires-python = ">=3.8"
authors = [{ name = "Yunhao Qian", email = "yunhaoq@seas.upenn.edu" }]
description = "Python bindings for Monte Carlo Tree Search in Othello."
readme = "README.md"
classifiers = ["License :: OSI Approved :: MIT License"]

[project.urls]
Homepage = "https://github.com/yunhao-qian/Othello-AlphaZero"

[tool.scikit-build]
# Protect the configuration against future changes in scikit-build-core.
minimum-version = "0.4"

# Setuptools-style build caching in a local directory.
build-dir = "build/{wheel_tag}"

# Build stable ABI wheels for CPython 3.12+.
wheel.py-api = "cp312"
